const SEARCH_FILM = 'SEARCH_FILM';
const FETCH_FILMS = 'FETCH_FILMS';
const FETCH_FILM_DETAILS = 'FETCH_FILM_DETAILS';
const LOADING = 'LOADING';
const FILTER_FILM = 'FILTER_FILM';

export {
  SEARCH_FILM, FETCH_FILMS, FETCH_FILM_DETAILS, LOADING, FILTER_FILM,
};
